name: CI Workflow

# Trigger workflow on every push to master or pull requests to main
on:
  push:
    branches: [master]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run WebDriverIO tests
      - name: Run WebDriverIO tests
        run: npx wdio run wdio.conf.js
